stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "268060978153.dkr.ecr.ap-southeast-5.amazonaws.com/greataihack1"
  NODE_ENV: "production"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache python3 py3-pip bash
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 268060978153.dkr.ecr.ap-southeast-5.amazonaws.com
  script:
    - docker build -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest

deploy:
  stage: deploy
  image: amazon/aws-cli
  script:
    - aws ecs update-service --cluster my-ecs-cluster --service my-ecs-service --force-new-deployment
