name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-5

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-5 | docker login --username AWS --password-stdin 242038040781.dkr.ecr.ap-southeast-5.amazonaws.com

      - name: Build Docker image
        run: |
          docker build --no-cache -t myapp:${{ github.sha }} .
          docker tag myapp:${{ github.sha }} 242038040781.dkr.ecr.ap-southeast-5.amazonaws.com/my-ecr-repo:${{ github.sha }}

      - name: Push Docker image to ECR
        run: |
          docker push 242038040781.dkr.ecr.ap-southeast-5.amazonaws.com/my-ecr-repo:${{ github.sha }}

      - id: task-def
        name: Update ECS task definition with new image
        run: |
          # Fetch current task definition
          aws ecs describe-task-definition --task-definition nextjs-task:1 \
            --query "taskDefinition" \
            --output json > taskdef.json

          NEW_IMAGE="242038040781.dkr.ecr.ap-southeast-5.amazonaws.com/my-ecr-repo:${{ github.sha }}"
          
          # Create new task definition with updated image and environment variables
          jq --arg IMAGE "$NEW_IMAGE" --arg OPENAI_KEY "${{ secrets.OPENAI_API_KEY }}" '
            {
              family: .family,
              taskRoleArn: .taskRoleArn,
              executionRoleArn: .executionRoleArn,
              networkMode: .networkMode,
              containerDefinitions: .containerDefinitions,
              volumes: .volumes,
              placementConstraints: .placementConstraints,
              requiresCompatibilities: .requiresCompatibilities,
              cpu: .cpu,
              memory: .memory,
              runtimePlatform: .runtimePlatform
            } |
            .containerDefinitions[0].image = $IMAGE |
            .containerDefinitions[0].environment = (
              (.containerDefinitions[0].environment // []) | 
              map(select(.name != "OPENAI_API_KEY"))
            ) + [{"name": "OPENAI_API_KEY", "value": $OPENAI_KEY}] |
            if .taskRoleArn == null then del(.taskRoleArn) else . end |
            if .volumes == null or .volumes == [] then del(.volumes) else . end |
            if .placementConstraints == null or .placementConstraints == [] then del(.placementConstraints) else . end |
            if .runtimePlatform == null then del(.runtimePlatform) else . end
          ' taskdef.json > new-taskdef.json

          # Debug: Show the new task definition
          echo "New task definition:"
          cat new-taskdef.json

          # Register new task definition
          TASKDEF_ARN=$(aws ecs register-task-definition --cli-input-json file://new-taskdef.json --query 'taskDefinition.taskDefinitionArn' --output text)
          
          if [ -z "$TASKDEF_ARN" ]; then
            echo "Error: Failed to register task definition"
            exit 1
          fi
          
          echo "New task definition ARN: $TASKDEF_ARN"
          echo "taskdef_arn=$TASKDEF_ARN" >> $GITHUB_OUTPUT

      - name: Update ECS Service to use new task definition
        run: |
          echo "Updating ECS service with new task definition..."
          echo "Task Definition ARN: ${{ steps.task-def.outputs.taskdef_arn }}"
          
          aws ecs update-service \
            --cluster my-app-cluster \
            --service nextjs-task-service-t2q09utt \
            --task-definition "${{ steps.task-def.outputs.taskdef_arn }}" \
            --force-new-deployment

      - name: Wait for service to stabilize
        run: |
          echo "Waiting for service to stabilize..."
          aws ecs wait services-stable \
            --cluster my-app-cluster \
            --services nextjs-task-service-t2q09utt